package meetings.dto;

public enum ScheduleMeetingFailure {
    MEETING_DATE_MUST_BE_3_DAYS_IN_ADVANCE,
    USER_IS_NOT_GROUP_ORGANIZER,
    GROUP_ORGANIZER_DOES_NOT_HAVE_ACTIVE_SUBSCRIPTION,
    PROPOSED_MEETING_HOST_DOES_NOT_HAVE_ACTIVE_SUBSCRIPTION,
    GROUP_MEETING_DOES_NOT_EXIST
}