package meetings.dto;

public enum SignUpForMeetingFailure {
    MEETING_DOES_NOT_EXIST,
    MEETING_HOST_CANNOT_SIGN_UP_FOR_MEETING,
    NO_FREE_ATTENDEE_SLOTS,
    USER_IS_NOT_GROUP_MEMBER, GROUP_MEMBER_IS_NOT_SUBSCRIBED
}